[shopondo_ticket]
title = "공상온도 스토어 ─ 티켓"
url = "http://shopondo.cafe24.com/product/list.html?cate_no=55"
entrySelector = "ul.prdList.column4 li.item.xans-record-"
titleSelector = "p.name span[style='font-size:12px;color:#555555;']:nth-child(2)"
linkSelector = "div.box a[name^='anchorBoxName']"
contentSelector = "span[style='font-size:12px;color:#555555;font-weight:bold;']:nth-child(2)"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[shopondo_records]
title = "공상온도 스토어 ─ 음반"
url = "http://shopondo.cafe24.com/product/list.html?cate_no=60"
entrySelector = "ul.prdList.column4 li.item.xans-record-"
titleSelector = "p.name span[style='font-size:12px;color:#555555;']:nth-child(2)"
linkSelector = "div.box a[name^='anchorBoxName']"
contentSelector = "span[style='font-size:12px;color:#555555;font-weight:bold;']:nth-child(2)"
imageSelector = "img.thumb"
waitUntil = "networkidle"